### ISSUE TITLE
Building Problem

### ISSUE THREAD

**Issue by qu-tan-um** [prakashmurali/TriQ#1]
- If I use `./configure` straight from the readme, it says
```
-bash: ./configure: No such file or directory
```
- If I use `autoconf`, it says
```
configure.ac:2: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```
Then, I use `./configure`, it says
```
./configure: line 1742: AM_INIT_AUTOMAKE: command not found
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
configure: creating ./config.status
config.status: creating Makefile
```
At last, I use `make`, it says
```
Makefile:15: *** missing separator.  Stop.
```

**Comment by prakashmurali** [comment]
Thanks for pointing out the issue.
The configure build seems to be broken. I've created a new Makefile in the base directory. Please add your Z3 include path to that directory and do 'make' to compile.

**Comment by qu-tan-um** [comment]
I added `/Users/tanbochendaniel/opt/anaconda3/envs/quantum/lib/python3.6/site-packages/z3/include` which contains `z3.h`. Then I used `make` and now I have 
```
g++ -o triq src/backtrack.o src/circuit.o src/expt.o src/gate.o src/machine.o src/mapper.o src/optimize_1q.o src/pattern.o src/quaternion.o src/targetter.o -lz3 -lboost_system 
ld: library not found for -lz3
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [triq] Error 1
```
I suspect this is still something to do with z3?

**Comment by prakashmurali** [comment]
You need to add the z3 library location to your LD_LIBRARY_PATH.

**Comment by qu-tan-um** [comment]
I think I successfully built TriQ. 

I tried [this file](https://github.com/epiqc/ScaffCC/blob/master/nisq_benchmarks/benchmarks/adder/adder.qasm) with 
```python ir2dag.py adder.qasm adder.in```
 and then 
```./triq adder.in adder.out ibmqx5```. 
Then it says 
```Segmentation fault: 11```.

**Comment by prakashmurali** [comment]
Can you try passing a extra command line arg "0"
  ./triq adder.in adder.out ibmqx5 0
There are three SWAP insertion methods that are used in the code for now. Sorry for the clunky interface.

**Comment by qu-tan-um** [comment]
I added `0` and it indeed started working. There're lots of intermediate information, but I think the final results are
```
...
Qubit Mapping
(0,7)
(1,10)
(2,11)
(3,6)
Best reliab:0.558002
PROG adder.in MACHINE ibmqx5 MAPPER_TIME 4 BACKTRACK_TIME 0
Assertion failed: (case1 || case2 || case3), function optimize, file src/optimize_1q.cpp, line 175.
Abort trap: 6
```
I suppose this isn't 100% successful, as some assertion failed?

**Comment by qu-tan-um** [comment]
The above happened on my Mac. On a Linux 16.04 server, I think it worked fine. The final results are
```
Qubit Mapping
(0,11)
(1,10)
(2,7)
(3,6)
Best reliab:0.555694
PROG adder.in MACHINE ibmqx5 MAPPER_TIME 4 BACKTRACK_TIME 0
fname:adder.out
Num CX:10
Done!
```
